version: '3.7'


x-db-config: &db-config
  DATABASE_NAME: ${DATABASE_NAME}
  DATABASE_HOST: ${DATABASE_HOST}
  DATABASE_PORT: ${DATABASE_PORT}
  DATABASE_USER: ${POSTGRES_USER}
  DATABASE_PASSWORD: ${POSTGRES_PASSWORD}

services:

  api:
    build: .
    container_name: api
    restart: unless-stopped
    ports:
      - ${API_PORT}:${API_PORT}
    networks:
      - mynetwork
    depends_on:
      - pgadmin
    env_file:
      - .env
    volumes:
      - ./sonet:/app:cached
      - ~/.ssh:/root/.ssh
      - ~/.bash_history:/root/.bash_history
    command: python main.py

  db:
    image: postgres:15.2-alpine
    container_name: postgre
    restart: always
    ports:
      - 5431:5431
      - 5433:5433
    networks:
      - mynetwork
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  pgadmin:
    container_name: pgadmin
    depends_on:
      - db
    restart: always
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 5050:80
    networks:
      - mynetwork

  web:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
    networks:
      - mynetwork
    volumes:
      - ./web:/etc/nginx/conf.d:ro
      - ~/.ssh:/root/.ssh
    restart: always

networks:
  mynetwork:
    driver: bridge
